version: '3.4'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=casher
      - POSTGRES_PASSWORD=casher
      - POSTGRES_USER=casher
    volumes:
      - psqldata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "casher", "-d", "casher"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  web:
    build: .
    command: sh ./deploy/entrypoint.sh
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    volumes:
      - media:/app/media:rw
      - static:/app/static:rw
    env_file:
      - .env

  nginx:
    image: nginx
    volumes:
      - ./deploy/web.conf:/etc/nginx/conf.d/default.conf:ro
      - media:/media:ro
      - static:/static:ro
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  media:
  static:
  psqldata: