# Generated by Django 4.2.2 on 2023-06-13 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=25, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("OUT", "Out"), ("IN", "In")], max_length=3
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issuer", models.CharField(max_length=60)),
                ("amount_dollar", models.DecimalField(decimal_places=2, max_digits=11)),
                ("amount_sum", models.DecimalField(decimal_places=2, max_digits=11)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dolar_price", models.DecimalField(decimal_places=2, max_digits=11)),
                ("issued", models.DateTimeField(db_index=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="casher.category",
                    ),
                ),
            ],
        ),
    ]
