# Generated by Django 4.2.2 on 2023-06-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="amount_dollar",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name="action",
            name="amount_sum",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
